@host = http://localhost:8787

###
GET {{host}}/api/v1

###
POST {{host}}/api/v1/conversations/start
Content-Type: application/json

{
  "message": "初心者にもわかりやすい、RailsのAPI実装記事を作りたい。"
}

###

POST {{host}}/api/v1/conversations/1c0c86d6-ea23-418f-9a45-d67cbd073b3b/ask
Content-Type: application/json

{
  "message": "認証APIを実装する記事を作りたい。"
}

###
GET {{host}}/api/v1/conversations/1
Content-Type: application/json

###
GET {{host}}/api/v1/conversations/1/messages
Content-Type: application/json

###
GET {{host}}/api/v1/documents
Content-Type: application/json

###
GET {{host}}/api/v1/documents/1
Content-Type: application/json

###
POST {{host}}/api/v1/conversations/1c0c86d6-ea23-418f-9a45-d67cbd073b3b/create-document
Content-Type: application/json

{
  "message": "認証APIを実装する記事を作りたい。"
}
