@host = http://localhost:8787

###
GET {{host}}/api/v1

###
POST {{host}}/api/v1/conversations/start
Content-Type: application/json

{
  "message": "my message"
}

###

POST {{host}}/api/v1/conversations/1/ask
Content-Type: application/json

{
  "message": "my message"
}

###
GET {{host}}/api/v1/conversations/1
Content-Type: application/json
